name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
       uses: github/super-linter@v4
       
      -name: Run Super-Linter
       uses: github/super-linter@v4
       env:
        Default_Branch: master
        GITHUB_Token: ${{ secrets.GITHUB_TOKEN }}
